#pragma once

void noAuto();
void testEzDrive();
void testEzTurn();
void testLLDrive();
void testLLTurn();
void redNeg();
void driveToLadder();
void RedPosBlueNeg2AWP();
void RedNegBluePos2AWP();
void RedPosBlueNeg3AWP();
void RedNegBluePos3AWP();
void redPosRush();
void bluePosRush();
void redNegRush();
void blueNegRush();
void Skills();
void Skills1();